SkyJSTranslationsLoaded({
    "btn_get_started" : "Comenzar",
    "btn_ok" : "Aceptar",
    "btn_close" : "Cerrar",
    "btn_continue" : "Continuar",
    "lnk_start_call" : "Llamar",
    "lnk_learn_more" : "Más información acerca de Skype",
    "lnk_learn_more_about_outlook" : "Más información sobre Skype para Outlook.com",
    "lnk_learn_more_about_account_merging" : "Más información sobre la fusión de cuentas",
    "lnk_get_skype" : "Descargar Skype",
    "msg_setup_info_in_title" : "{INVITER} quiere hacerte una llamada gratis con Skype.",
    "msg_setup_info_in" : "Descarga el complemento de Skype y, tras una única y rápida instalación, estarás conectado.",
    "msg_setup_info_out" : "Para llamar a {INVITER}, necesitarás descargar el complemento de Skype; su instalación es rápida y solo tendrás que hacerla una vez.",
    "msg_setting_up_info" : "La descarga ha comenzado. Sigue las instrucciones para guardar y ejecutar el complemento de Skype.",
    "msg_just_a_moment" : "Solo un momento...",
    "msg_click_save_file" : "Haz clic en \"Guardar archivo\"",
    "msg_run_downloaded_file" : "Ejecuta el archivo descargado",
    "msg_ready_to_start_calling" : "Listo para comenzar la llamada",
    "msg_download_too_long" : "Si tu descarga se interrumpe o tarda demasiado, puedes {LINK_RESTART_MANUALLY}reiniciarla manualmente{LINK_END} o descargar ahora la {LINK_GET_SKYPE_APP}aplicación completa de Skype{LINK_END}.",
    "msg_setup_complete" : "Se ha completado la configuración. Estás listo para iniciar la llamada con {INVITER}",
    "msg_setup_complete_call_inviter" : "La configuración se ha completado. Puedes llamar a {INVITER} ahora.",
    "msg_enjoy_skype_call" : "¡Que disfrutes de tu llamada de Skype con {INVITER}!",
    "msg_invite_expired" : "Lo sentimos, pero el vínculo para la llamada ya no está disponible.",
    "msg_ask_for_link" : "Si deseas uno nuevo, pídele a {INVITER} que vuelva a llamarte. O bien, descarga Skype para llamar gratis cuando desees.",
    "msg_cookies_disabled" : "Las cookies están deshabilitadas",
    "msg_cookies_disabled_ext" : "Las cookies no están habilitadas en tu explorador. Para continuar, cambia la configuración correspondiente en las opciones de seguridad.",
    "msg_install_plugin_outlook" : "Instala el complemento de Skype para hacer llamadas desde Outlook.com",
    "msg_install_plugin_and_call_from_outlook" : "Instala el complemento de Skype para hacer llamadas desde Outlook.com",
    "msg_play_video" : "Reproducir video",
    "msg_wrong_user" : "Has iniciado sesión como un usuario diferente",
    "msg_wrong_user_text" : "Has recibido una invitación para hacer una llamada, pero has iniciado sesión en una cuenta de Microsoft diferente de la que debía recibir esta invitación. Para que la llamada pueda realizarse, descarga Skype o inicia sesión usando otra cuenta de Microsoft.",
    "ttl_skype_calling_setup" : "Configuración de las llamadas de Skype",
    "lnk_tou_agree" : "Acepto. Continuar",
    "lnk_tou_disagree" : "En otro momento; gracias",
    "msg_voice_and_video" : "Videollamadas y llamadas gratuitas",
    "msg_easily_ims" : "Envía mensajes instantáneos incluso durante una llamada",
    "msg_call_your_buddies" : "Llama a todos tus contactos de Messenger",
    "msg_bring_skype_contacts" : "Importa tus contactos de Skype a Outlook.com",
    "msg_before_we_start" : "Antes de comenzar\u2026",
    "msg_you_must_agree" : "Debes aceptar las {LINK_TERMS}Condiciones de Uso{LINK_END}y la {LINK_PRIVACY}Política de Privacidad{LINK_END} de Skype.",
    "msg_before_we_start_you_must_agree" : "Antes de empezar, debes aceptar las {LINK_TERMS}Condiciones de Uso{LINK_END} y la {LINK_PRIVACY}Política de Privacidad{LINK_END} de Skype.",
    "msg_inform_me_about_new_products" : "Informarme por correo electrónico acerca de nuevos productos, características y ofertas especiales.",
    "msg_would_you_like_to_merge" : "¿Deseas combinar tus cuentas de Skype y Microsoft para ver tus contactos de Skype en Outlook.com?",
    "msg_skype_account_to_merge" : "Introduce los datos de tu cuenta de Skype",
    "alt_back" : "Volver",
    "plh_skype_name" : "Nombre de usuario",
    "plh_password" : "Contraseña",
    "val_sign_in" : "Iniciar sesión",
    "lnk_problems_signing_in" : "¿No puedes iniciar sesión?",
    "msg_reach_your_skype_contacts_in_outlook_and_call" : "Ahora puedes comunicarte con tus contactos de Skype y Messenger en Outlook.com.",
    "msg_can_not_connect_to_skype_server" : "Lo sentimos, pero no podemos conectar con el servidor de Skype. Inténtalo de nuevo en otro momento.",
    "ttl_age_limit" : "Lo sentimos, pero existe un límite de edad",
    "txt_age_limit" : "No puedes iniciar sesión en Skype con esta cuenta de Microsoft porque no alcanzas el límite de edad para tu país.",
    "ttl_problem_signing_in" : "Ocurrió un problema al iniciar sesión",
    "msg_problem_signing_in" : "Has intentado iniciar sesión sin éxito demasiadas veces. Espera un minuto e inténtalo de nuevo.",
    "ttl_not_signed_in" : "No has iniciado sesión en live.com",
    "msg_not_signed_in" : "No iniciaste sesión en live.com. Primero inicia sesión y después, inténtalo de nuevo.",
    "lnk_cancel_and_change_account" : "Cancelar y cambiar cuenta",
    "msg_check_your_details" : "Lo sentimos, se produjo un error. Verifica tus detalles.",
    "msg_setup_is_complete_ready_to_calling" : "Se ha completado la configuración. Estás listo para comenzar a llamar.",
    "msg_how_to_make_a_call" : "Cómo hacer una llamada",
    "msg_click_on_chat_icon" : "Haz clic en el icono del chat en la esquina superior derecha",
    "msg_select_person_to_call" : "Selecciona a la persona a quien deseas llamar",
    "msg_click_on_video_or_voice_call_buttons" : "Haz clic en el botón de videollamada o de llamada",
    "msg_need_more_help" : "¿Necesitas más ayuda?",
    "lnk_watch_this_video" : "Mira este video",
    "msg_accounts_is_already_merged" : "La cuenta ya está fusionada",
    "msg_account_is_already_merged" : "La cuenta de Skype {SKYPE_ACCOUNT} ya está combinada con otra cuenta de Microsoft.",
    "msg_what_you_can_do" : "Puedes hacer lo siguiente:",
    "msg_use_existing_merged_skype_account" : "Iniciar sesión en Outlook.com con una cuenta de Microsoft diferente.",
    "msg_merge_your_accounts" : "Un último paso: combina tus cuentas",
    "msg_merge_this_microsoft_account" : "{LINK_MERGE}Fusionar esta cuenta de Microsoft{LINK_END} con otra cuenta de Skype.",
    "msg_create_a_brand_new_skype_account" : "{LINK_NEW_ACCOUNT}Crear una cuenta de Skype completamente nueva{LINK_END} (y después, si lo deseas, fusionarla con esta cuenta de Microsoft).",
    "lnk_get_more_help_with_account_merging" : "Obtener más ayuda con la fusión de cuentas",
    "btn_i_have_skype_account" : "Tengo una cuenta de Skype",
    "btn_new_to_skype" : "No, soy nuevo en Skype",
    "msg_generic_error" : "Ocurrió un problema",
    "msg_generic_error_text" : "Parece que Skype para Outlook.com no se encuentra disponible en este momento. Inténtalo de nuevo más tarde o descarga ahora la aplicación completa de Skype.",
    "msg_rollback" : "Ocurrió un problema. Parece que Skype para Outlook.com no se encuentra disponible en este momento. Inténtalo de nuevo más tarde o descarga ahora la aplicación completa de Skype.",
    "btn_download_skype" : "Descargar Skype",
    "ttl_metro_plugin_not_supported" : "Descarga Skype desde la tienda",
    "msg_metro_plugin_not_supported" : "Tu versión de Internet Explorer actualmente no admite el complemento de Skype para Outlook.com. Pero no te preocupes porque hay una nueva versión de Skype rápida y atractiva esperándote en la tienda. ¡Y es gratis!",
    "msg_metro_plugin_not_supported_winrt" : "Tu versión de Windows actualmente no admite el complemento de Skype para Outlook.com. Pero no te preocupes porque hay una nueva versión de Skype rápida y atractiva esperándote en la tienda. ¡Y es gratis!",
    "msg_skype_for_metro" : "Lo sentimos, pero Skype para Outlook.com no es compatible con este explorador. Descarga la versión más reciente de Skype para Windows 8 y podrás disfrutar de la mejor experiencia.",
    "btn_get_skype_for_metro" : "Descargar Skype para Windows RT",
    "ttl_skype_plugin_update" : "Tu complemento de Skype debe actualizarse",
    "msg_skype_plugin_update" : "Para hacer esta llamada de Skype, necesitarás descargar la versión más reciente.",
    "btn_update_plugin" : "Actualizar complemento",
    "ttl_after_instalation_continue" : "Cuando finalice la instalación, haz clic en Continuar",
    "ttl_heres_what_todo_next" : "Esto es lo que debes hacer a continuación:",
    "msg_select_run" : "Selecciona Ejecutar",
    "msg_your_skype_plugin_installs" : "Tu complemento de Skype se instala",
    "msg_thats_it_start_calling" : "Y listo, comienza a llamar",
    "ttl_your_skype_is_downloading" : "El complemento de Skype se está descargando. No tardará mucho...",
    "ttl_plugin_download_error" : "No se pudo descargar el complemento de Skype para Outlook.com",
    "txt_ie10_window8_error" : "Internet Explorer 10 para Windows 8 actualmente no admite este complemento. Pero puedes descargar la aplicación completa de Skype desde la Tienda.",
    "msg_reinstall_outgoing" : "Para llamar a {INVITER}, debes actualizar tu complemento de Skype. Tardará muy poco.",
    "msg_reinstall_incoming" : "Para hablar con {INVITER}, primero debes actualizar tu complemento de Skype. Tardará muy poco.",
    "ttl_pluginInstall" : "La descarga ha comenzado. ¿Y ahora qué?",
    "msg_pluginInstall_msie_step1" : "Cuando finalice, ejecuta el instalador del complemento de Skype.",
    "msg_pluginInstall_msie_step2" : "Haz clic en \u201CSí\u201D para aceptar la configuración del Control de cuentas de usuario.",
    "msg_pluginInstall_chrome_win_step1" : "Ejecuta el instalador del complemento de Skype, que está en la esquina inferior izquierda del explorador.",
    "msg_pluginInstall_chrome_win_step2" : "Haz clic en \u201CSí\u201D para aceptar la configuración del Control de cuentas de usuario.",
    "msg_pluginInstall_firefox_win_step1" : "Haz clic en \u201CGuardar archivo\u201D cuando se te solicite.",
    "msg_pluginInstall_firefox_win_step2" : "Haz doble clic en \u201CSkypeWebPlugin.msi\u201D en la ventana de descargas.",
    "msg_pluginInstall_safari_step1" : "El complemento de Skype se descargará en tu equipo.",
    "msg_pluginInstall_safari_step2" : "Ejecuta el archivo que has descargado y sigue las instrucciones.",
    "msg_pluginInstall_step3" : "Ya puedes comenzar a llamar.",
    "msg_setup_info_preview_title" : "¡Te damos la bienvenida! Prueba Skype hoy mismo.",
    "msg_skype_call" : "Llamada de Skype",
    "msg_plugin_not_installed_yet" : "Aparentemente, el complemento aún no está instalado. Sigue estas instrucciones.",
    "btn_next" : "Siguiente",
    "msg_select_next_after_plugin_is_installed" : "Una vez que hayas instalado el complemento, selecciona \"Siguiente\".",
    "btn_let_get_started" : "Comencemos",
    "msg_plugin_download_started" : "La descarga ha comenzado.",
    "msg_select_next" : "Una vez que hayas instalado el complemento, selecciona \"Siguiente\".",
    "btn_toast_answer_video" : "Iniciar videollamada",
    "btn_toast_answer_audio" : "Iniciar llamada ",
    "btn_toast_decline" : "Rechazar llamada"
});